require("plugins.transparent")
require("plugins.colorscheme")
require("plugins.harpoon")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.code_runner")
require("plugins.undotree")
require("plugins.lualine")
require("pretty-fold")
require("plugins.autoclose")
-- require("plugins.nvim-tree")
